# Generated by Django 4.2.3 on 2023-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hallo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
