# Generated by Django 4.2.3 on 2023-08-03 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joinedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
